---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements.yml
    requirements-file: collections.yml
lint: |
    yamllint .
    ansible-lint
    flake8
driver:
  name: docker
platforms:
  - name: instance-${TOX_ENVNAME}
    image: ${MOLECULE_DISTRO:-'fedora:latest'}
    dockerfile: ../resources/Dockerfile.j2
    cgroupns_mode: host
    pre_build_image: false
    command: /sbin/init
    tmpfs:
      - /run
      - /run/lock
      - /tmp:exec
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbooks/converge.yml
verifier:
  name: testinfra
  directory: ../shared/tests
  env:
    MOLECULE_SCENARIO: "default"
  options:
    verbose: true
